//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownicy
    {
        public int Id { get; set; }
        public string ImieNazwisko { get; set; }
        public string Dział { get; set; }
        public string Wynagrodzenie { get; set; }
    }
}
